### ISSUE TITLE
1.51 incompatible menu resources?

### ISSUE THREAD

**Issue by thoni56** [DavidKinder/Windows-Glk#15]
When building WinArun (the Alan IF interpreter using WindowsGLK) with 1.5.0 the menues look like this:
![image](https://user-images.githubusercontent.com/204496/120116143-f1b6ce80-c186-11eb-8d86-b4ba6004a2aa.png)

Building against 1.5.1 I get:
![image](https://user-images.githubusercontent.com/204496/120116161-0bf0ac80-c187-11eb-85c0-fcc19c50b6cb.png)

Not so nice ;-) (The left one triggers the scrollback and the right one the option dialogue.)

I could not find any changes that would require changes to the "client" resource files. The Test example seems to be  doing the same thing as I am.

Any ideas?

**Comment by DavidKinder** [comment]
At a guess, your application doesn't have a manifest? You'll need to add one and make sure it turns on v6 of the common controls, as otherwise the toolbar control doesn't seem to like the new-style 32-bit icons.

**Comment by thoni56** [comment]
Yes, that worked. Thank you!

**Comment by DavidKinder** [comment]
Hmmm, nothing obvious comes to mind. I'm not completely sure I'm clear on what the problem now is, can you do another screenshot?

**Comment by thoni56** [comment]
So the app icon is working, as is the menues. The current mystery is that the options shortcut "submenu" that was available with 1.50 is not:
![image](https://user-images.githubusercontent.com/204496/120278706-e7472280-c2b5-11eb-8870-f3d674660aff.png)

**Comment by DavidKinder** [comment]
Sorry, but I'm not sure what you mean by 'the options shortcut "submenu"'...

**Comment by thoni56** [comment]
Sorry, "submenu" is probably not the Windowsy word, "toolbar", maybe?

Maybe I should have included the very first screen clip again... But if you compare the last clip to that you see that in the first (which is from 1.50) there is a row of icons below the menu items with "copy", "font selection" and "checkboxes". They are not visible in the last clip.

I thought those were from WindowsGlk?

**Comment by DavidKinder** [comment]
Ah, okay, "toolbar" is the right term. I did change the default toolbar around for Windows Glk 1.51.

In Windows Glk 1.50, the toolbar is below the menu, and there should be icons for, in order, "scrollback", "proportional font", "fixed width font", "options dialog" and, if there is one, "help file". In Windows Glk 1.51 I put the toolbar to the right of the menus to avoid wasting so much window space, and the font toolbar items got removed, since they're accessible from the options dialog anyway. What you should see should match ![this image](Counterfeit%20Monkey.png). In this there are three icons: a scroll (for scrollback), a tick (for options) and a question mark (for the help file, this won't be there if Arun doesn't provide one).

**Comment by thoni56** [comment]
Ok, good. So, since that toolbar is not there, there is still something amiss with how I define my resources. At least that's good to know ;-) I'll keep digging.

**Comment by DavidKinder** [comment]
It should be just there without you having to do anything ... Is the toolbar there for the example programs if you compile them? What are you using as your compiler?

**Comment by thoni56** [comment]
Yes, I'm actually cheating ;-) and building with Cygwin's cross-compiler. The test example suffers from the same "issue" so that might well be the problem. (Which is worse because then I need to investigate that resource compiler...)

I'll install Visual Studio and try to build the Test example via the solution to see if that works.

**Comment by DavidKinder** [comment]
My initial reaction is that the resources in the executable shouldn't affect whether the toolbar is there or not. So I'm not sure what's going on. The first thing I would try is to download the latest release of Windows Glulxe (https://github.com/DavidKinder/Windows-Glulxe/releases) and grab a Glulx game from http://ifarchive.org/indexes/if-archive/games/glulx/ and see if the toolbar works with that. If it doesn't, then it's something about your system...

**Comment by thoni56** [comment]
Found it. It was a missing define in my `resource.h`, namely IDR_MANIFEST which kind of became necessary when the manifest was added ;-) Don't know how it happened to make it partly work there for a while there, a clear red herring...

Thanks for your moral support and pointers!

**Comment by DavidKinder** [comment]
Good to hear you've got it working!
