### ISSUE TITLE
Missing function giblorb_unload_chunk

### ISSUE THREAD

**Issue by cspiegel** [DavidKinder/Windows-Glk#17]
The function `giblorb_unload_chunk` appears to be missing from the DLL (I'm using the 1.51 binary download provided here).  The function does exist in `gi_blorb.c`.

This is on MinGW, if it matters.  I can build against Windows Glk just fine, in general, but when I use `giblorb_unload_chunk`, I get a link error.  I suspect it's just missing from `Glk.def` but I don't have Visual Studio so I can't test adding it and rebuilding.

**Comment by DavidKinder** [comment]
`giblorb_load_image_info` is missing, too.

**Comment by DavidKinder** [comment]
Fixed by 302c895be72e47b97d75016a0b918fbfd3b5e62d.
