### ISSUE TITLE
Glulxe fatal error: reference to a nonexistent GLK object when trying to save games created with superglux

### ISSUE THREAD

**Issue by sukiletxe** [DavidKinder/Windows-Glk#4]
(Sorry if this issue doesn't belong here. I couldn't find a repository dedicated to Glulxe.)
Maybe this doesn't have anything to do with Superglux, but the games I tested where written using that system. Saving worked in previous version of Glulxe (I don't know which ones, though).

**Comment by curiousdannii** [comment]
Here's the Glulxe repo: https://github.com/erkyrath/glulxe

**Comment by sukiletxe** [comment]
Ah, thank you. I thought there was a windows-specific  port of it. 
Posting this there and closing this.
