### ISSUE TITLE
There should be no sound notification when a MOD is stopped prematurely

### ISSUE THREAD

**Issue by angstsmurf** [DavidKinder/Windows-Glk#5]
This is a nitpick, but according to [the Glk spec](https://eblong.com/zarf/glk/glk-spec-074_8.html), sound notification events should only fire when a sound reaches its end, and not when it is stopped or interrupted.

It seems that when you begin playing a MOD sound in Windows Glulxe, any MOD already playing on another channel will be stopped (because the Modplug library only supports playing one MOD at a time, I suppose). This will issue a sound notification.

If I'm reading [8.3: Playing Sounds](https://eblong.com/zarf/glk/glk-spec-074_8.html#s.3) correctly, the play functions are supposed to return 0 (error) and refuse to play the new MOD in this situation, and not generate any sound notification.

This behavior can be tested with the TEST MOD command in my [Glulx sound test](https://github.com/angstsmurf/soundtest/releases).

**Comment by DavidKinder** [comment]
I agree, Windows Glk looks to be getting this wrong. I'll have this fixed for the next release.

**Comment by DavidKinder** [comment]
Fixed by commit https://github.com/DavidKinder/Windows-Glk/commit/be0679494679401cb75ee950670253a0ab890822
